[package]
name = "tui-video-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.25.9"
imageproc = "0.26.0"
termcolor = "1.4.1"
termion = "4.0.6"
nokhwa = { version = "0.10.3", features=["input-native", "output-threaded"] }
